/**
 * PocketBase Collection Types
 * 
 * These types define the schema for all collections in PocketBase.
 * Run `bun run typegen` after creating collections to auto-generate from DB.
 */

// Base record fields (auto-generated by PocketBase)
export interface BaseRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: string;
}

// ============ SUBJECTS ============
export interface SubjectRecord extends BaseRecord {
  name: string;
  shortName: string;
  color: string;
  requiresLab: boolean;
}

// ============ TEACHERS ============
export interface TeacherRecord extends BaseRecord {
  name: string;
  subject: string; // relation to subjects
  weeklyLoad: number;
  unavailable: number[][]; // [[day, period], ...]
}

export interface TeacherExpanded extends TeacherRecord {
  expand?: {
    subject?: SubjectRecord;
  };
}

// ============ ROOMS ============
export interface RoomRecord extends BaseRecord {
  name: string;
  tags: string[];
}

// ============ DISCIPLINES ============
export interface SubjectAllocation {
  id: string;
  subjectId: string;
  totalPeriods: number;
  doublePeriods: number;
  singlePeriods: number;
  requiresLab: boolean;
}

export interface StaticCourse {
  id: string;
  name: string;
  day: number;
  period: number;
  color: string;
}

export interface DisciplineRecord extends BaseRecord {
  name: string;
  category: string;
  subjectAllocations: SubjectAllocation[];
  staticCourses: StaticCourse[];
}

// ============ CLASSES ============
export interface ClassRecord extends BaseRecord {
  name: string;
  category: string;
  discipline: string; // relation to disciplines
  formTeacher: string | null; // relation to teachers
}

export interface ClassExpanded extends ClassRecord {
  expand?: {
    discipline?: DisciplineRecord;
    formTeacher?: TeacherRecord;
  };
}

// ============ ASSIGNMENTS ============
export interface AssignmentRecord extends BaseRecord {
  class: string; // relation to classes
  subject: string; // relation to subjects
  teacher: string | null; // relation to teachers
}

export interface AssignmentExpanded extends AssignmentRecord {
  expand?: {
    class?: ClassRecord;
    subject?: SubjectRecord;
    teacher?: TeacherRecord;
  };
}

// ============ TIME GRID ============
export interface PeriodTime {
  period: number;
  startTime: string;
  endTime: string;
}

export interface Break {
  id: string;
  name: string;
  duration: number;
  isHard: boolean;
  afterPeriod: number;
}

export interface DaySchedule {
  [key: number]: PeriodTime[];
}

export interface TimeGridRecord extends BaseRecord {
  workDays: number;
  periodsPerDay: number;
  breaks: Break[];
  daySchedules: DaySchedule;
  // New fields
  selectedDays?: number[];
  schoolStartDate?: string;
  schoolStartTime?: string;
  minutesPerPeriod?: number;
}

// ============ TIMETABLE (Generated) ============
export interface TimetableEntry extends BaseRecord {
  class: string;
  day: number;
  period: number;
  subject: string;
  teacher: string;
  room?: string;
}

// Collection name to type mapping
export interface Collections {
  subjects: SubjectRecord;
  teachers: TeacherRecord;
  rooms: RoomRecord;
  disciplines: DisciplineRecord;
  classes: ClassRecord;
  assignments: AssignmentRecord;
  time_grid: TimeGridRecord;
  timetable: TimetableEntry;
}

export type CollectionName = keyof Collections;
